name: "datasus_ml_pipeline"
services:
    base_datapipeline: &base
        build:
            context: ./DataPipeline
            dockerfile: Dockerfile
        image: ml_datapipeline
        volumes:  
            - ./data:/app/data
            - ./models:/app/models
            - ./logs:/app/logs

    acquire:
        <<: *base
        container_name: acquire
        command: ["acquire"]

    process:
        <<: *base
        container_name: process
        command: ["process"]
        depends_on:
            acquire:
                condition:
                    service_completed_successfully

    train:
        <<: *base
        container_name: train
        command: ["train"]    
        depends_on:
            process:
                condition:
                    service_completed_successfully

    linkage:
        <<: *base
        container_name: linkage
        command: ["linkage"]
        depends_on:
            process:
                condition:
                    service_completed_successfully

    jupyter:
        container_name: jupyter
        build:
            context: ./EnsembleModels
            dockerfile: Dockerfile
        image: ml_jupyter
        ports:
            - 8888:8888
        environment:
            - UID=${UID:-1000}
            - GID=${GID:-1000}
            - CHOWN_HOME=yes
            - PYTHONPATH=/home/jovyan
        # user: root
        volumes:
            - ./EnsembleModels/notebooks:/home/jovyan/work
            - ./EnsembleModels/src:/home/jovyan/src
            - ./data:/home/jovyan/data
            - ./models:/home/jovyan/models
            - ./logs:/home/jovyan/logs
        command: start-notebook.sh --NotebookApp.token=
