datasets:
  SINASC:
    dataset_name: SINASC
    dataset_filename: sinasc

    start_year: 2020
    final_year: 2023

    columns:
      - DTNASC
      - CODMUNNASC
      - PARTO
      - SEXO
      - PESO
      - SEMAGESTAC
      - RACACOR
      - GRAVIDEZ
      - APGAR5
      - CONSPRENAT
      - IDANOMAL
      - IDADEMAE
      - TPROBSON

    transformations:
      filter:
        PESO:
          min: 350
          max: 6500

      rename:
        "CODMUNNASC": "CODMUN"

      binary_groups:
        TPROBSON: [1, 2, 3, 4, 6]

      thresholds:
        PESO: 2500
        SEMAGESTAC: 37

  SIM:
    dataset_name: SIM
    dataset_filename: sim

    start_year: 2020
    final_year: 2024

    columns:
      - IDADE
      - DTNASC
      - CODMUNNATU
      - PARTO
      - SEXO
      - PESO
      - SEMAGESTAC
      - RACACOR
      - GRAVIDEZ

    transformations:
      filter:
        IDADE:
          max: 228
        PESO:
          min: 350
          max: 6500

      rename:
        "CODMUNNATU": "CODMUN"

pre_linkage_cols:
  - DTNASC
  - CODMUN
  - PARTO
  - SEXO
  - PESO
  - SEMAGESTAC
  - RACACOR
  - GRAVIDEZ
  - unique_id
  - APGAR5
  - CONSPRENAT
  - IDANOMAL
  - IDADEMAE
  - bTPROBSON
  - tSEMAGESTAC
  - tPESO

ensemble_columns:
  - tSEMAGESTAC
  - tPESO
  - APGAR5
  - CONSPRENAT
  - IDANOMAL
  - RACACOR
  - bTPROBSON
  - IDADEMAE
  - OBITO
